version: '3'
services:
  # Worker service
  worker-service:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 1
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - service-network
    expose:
      - 8080
    ports:
      - 8080:8080

  # Postgres service
  postgres:
    image: postgres:latest
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: 45Odax2yTi*
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - service-network
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  service-network:
    driver: bridge

volumes:
    db-data: