version: '3'
services:
  # Postgres service
  postgres:
    image: postgres:latest
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: 45Odax2yTi*
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - service-network
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  service-network:
    driver: bridge

volumes:
  db-data: